import React, { useState, useEffect } from 'react';
import {
  Code2,
  ExternalLink,
  RotateCcw,
  Download,
  Package,
  Layers,
  Box,
  Check,
  FileCode,
  Sparkles
} from 'lucide-react';
import { CodeFile, Language, PreviewType } from '../types';
import { TRANSLATIONS } from '../utils/translations';

interface PreviewViewProps {
  files: CodeFile[];
  previewType: PreviewType;
  lang: Language;
  theme: 'dark' | 'light';
}

export const PreviewView: React.FC<PreviewViewProps> = ({
  files,
  previewType,
  lang,
  theme
}) => {
  const t = TRANSLATIONS[lang];
  const [activeFileIndex, setActiveFileIndex] = useState(0);
  const [isCopied, setIsCopied] = useState(false);
  const [downloadSuccess, setDownloadSuccess] = useState(false);
  const [iframeKey, setIframeKey] = useState(0);

  const isLight = theme === 'light';
  const isMcaddon = previewType === 'mcaddon' || files.some(f => f.name.includes('manifest.json') || f.name.includes('mcaddon'));

  // Get active file
  const activeFile = files[activeFileIndex] || files[0];

  useEffect(() => {
    if (activeFileIndex >= files.length) {
      setActiveFileIndex(0);
    }
  }, [files.length, activeFileIndex]);

  // Construct live HTML/JS sandbox for Web/Windows/Android
  const getSandboxSrcDoc = () => {
    if (!files || files.length === 0) return '';

    const htmlFile = files.find(f => f.name.endsWith('.html')) || files[0];
    const cssFile = files.find(f => f.name.endsWith('.css'));
    const jsFile = files.find(f => f.name.endsWith('.js') || f.name.endsWith('.ts'));

    let html = htmlFile?.content || '<div>No HTML content</div>';

    if (cssFile && !html.includes('<style>')) {
      html = `<style>${cssFile.content}</style>\n` + html;
    }

    if (jsFile && !html.includes('<script>')) {
      html = html + `\n<script>${jsFile.content}</script>`;
    }

    return html;
  };

  const handleDownloadActiveFile = () => {
    if (!activeFile) return;
    const blob = new Blob([activeFile.content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = activeFile.name;
    link.click();
    URL.revokeObjectURL(url);
    setDownloadSuccess(true);
    setTimeout(() => setDownloadSuccess(false), 2000);
  };

  const handleDownloadAllMcaddon = () => {
    // Generates .mcaddon structure
    const blob = new Blob([JSON.stringify({
      format_version: 2,
      header: {
        name: "Helfrex Custom Addon",
        description: "Generated by HelfrexAI Qwen 2.5 Coder",
        uuid: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
        version: [1, 0, 0],
        min_engine_version: [1, 20, 50]
      },
      files: files.map(f => ({ path: f.name, content: f.content }))
    }, null, 2)], { type: 'application/octet-stream' });

    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'helfrex_minecraft_mod.mcaddon';
    link.click();
    URL.revokeObjectURL(url);
    setDownloadSuccess(true);
    setTimeout(() => setDownloadSuccess(false), 2000);
  };

  return (
    <div className={`flex-1 flex flex-col h-full overflow-hidden ${isLight ? 'bg-slate-100/70' : 'bg-[#0f121a]'}`}>
      {/* Header bar */}
      <div
        className={`h-12 px-6 border-b flex items-center justify-between shrink-0 select-none ${
          isLight ? 'bg-white border-slate-200 shadow-sm' : 'bg-[#151a26] border-slate-800'
        }`}
      >
        <div className="flex items-center space-x-3">
          <Code2 className="w-5 h-5 text-indigo-500" />
          <h2 className={`text-xs font-bold uppercase tracking-wider ${isLight ? 'text-slate-900' : 'text-white'}`}>
            {t.preview.title}
          </h2>
          {isMcaddon && (
            <span className="text-[10px] bg-emerald-500/20 border border-emerald-500/40 text-emerald-400 font-bold px-2 py-0.5 rounded-full flex items-center gap-1">
              <Box className="w-3 h-3" /> Minecraft .mcaddon
            </span>
          )}
        </div>

        {/* Action Buttons */}
        <div className="flex items-center space-x-2">
          {files.length > 0 && !isMcaddon && (
            <button
              onClick={() => setIframeKey(k => k + 1)}
              className={`p-1.5 rounded-lg border text-xs flex items-center gap-1 transition ${
                isLight ? 'bg-slate-100 hover:bg-slate-200 border-slate-300 text-slate-700' : 'bg-slate-800 hover:bg-slate-700 border-slate-700 text-slate-300'
              }`}
              title={t.preview.refresh}
            >
              <RotateCcw className="w-3.5 h-3.5" />
            </button>
          )}

          {isMcaddon ? (
            <button
              onClick={handleDownloadAllMcaddon}
              className="px-3 py-1.5 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white font-bold text-xs flex items-center gap-1.5 shadow-sm transition active:scale-[0.98]"
            >
              <Download className="w-3.5 h-3.5" />
              <span>{downloadSuccess ? t.preview.downloadSuccess : t.preview.downloadMcaddonPackage}</span>
            </button>
          ) : (
            files.length > 0 && (
              <button
                onClick={handleDownloadActiveFile}
                className="px-3 py-1.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-bold text-xs flex items-center gap-1.5 shadow-sm transition active:scale-[0.98]"
              >
                <Download className="w-3.5 h-3.5" />
                <span>{downloadSuccess ? t.preview.downloadSuccess : t.preview.downloadFile}</span>
              </button>
            )
          )}
        </div>
      </div>

      {/* Main Preview Content */}
      <div className="flex-1 overflow-hidden p-4 md:p-6 flex flex-col">
        {files.length === 0 ? (
          <div className="h-full flex flex-col items-center justify-center text-center p-8 max-w-md mx-auto space-y-4">
            <div className={`w-16 h-16 rounded-2xl flex items-center justify-center ${
              isLight ? 'bg-indigo-50 text-indigo-500 border border-indigo-200' : 'bg-indigo-500/10 text-indigo-400 border border-indigo-500/20'
            }`}>
              <Code2 className="w-8 h-8" />
            </div>
            <h3 className={`text-sm font-bold ${isLight ? 'text-slate-900' : 'text-white'}`}>
              {t.preview.noCode}
            </h3>
            <p className={`text-xs leading-relaxed ${isLight ? 'text-slate-600' : 'text-slate-400'}`}>
              {t.preview.noCodeDesc}
            </p>
          </div>
        ) : isMcaddon ? (
          /* Minecraft Bedrock Addon Specialized Tree & Code Viewer */
          <div className="flex-1 flex flex-col md:flex-row gap-4 h-full overflow-hidden">
            {/* Left File Tree */}
            <div className={`w-full md:w-64 rounded-2xl border p-3.5 flex flex-col shrink-0 ${
              isLight ? 'bg-white border-slate-200 shadow-sm' : 'bg-[#141a27] border-slate-800'
            }`}>
              <div className="flex items-center gap-2 mb-3 pb-2 border-b border-slate-200 dark:border-slate-800">
                <Package className="w-4 h-4 text-emerald-500" />
                <span className={`text-xs font-bold uppercase tracking-wider ${isLight ? 'text-slate-900' : 'text-white'}`}>
                  {t.preview.packageTree}
                </span>
              </div>

              <div className="flex-1 overflow-y-auto space-y-1 pr-1">
                {files.map((file, idx) => (
                  <button
                    key={file.name}
                    onClick={() => setActiveFileIndex(idx)}
                    className={`w-full px-2.5 py-1.5 rounded-lg text-left text-xs font-mono flex items-center gap-2 transition ${
                      activeFileIndex === idx
                        ? 'bg-emerald-500/20 text-emerald-600 dark:text-emerald-300 font-bold border border-emerald-500/30'
                        : isLight
                        ? 'text-slate-700 hover:bg-slate-100'
                        : 'text-slate-400 hover:bg-slate-800/80 hover:text-white'
                    }`}
                  >
                    <FileCode className="w-3.5 h-3.5 shrink-0 text-emerald-500" />
                    <span className="truncate">{file.name}</span>
                  </button>
                ))}
              </div>

              <div className="pt-3 border-t border-slate-200 dark:border-slate-800 mt-2">
                <button
                  onClick={handleDownloadAllMcaddon}
                  className="w-full py-2 bg-emerald-600 hover:bg-emerald-500 text-white rounded-xl text-xs font-bold flex items-center justify-center gap-1.5 shadow-sm transition"
                >
                  <Download className="w-3.5 h-3.5" /> .mcaddon Dosyasını İndir
                </button>
              </div>
            </div>

            {/* Right Editor / Manifest Display */}
            <div className={`flex-1 rounded-2xl border flex flex-col overflow-hidden ${
              isLight ? 'bg-white border-slate-200 shadow-sm' : 'bg-[#141a27] border-slate-800'
            }`}>
              <div className={`h-10 px-4 border-b flex items-center justify-between shrink-0 ${
                isLight ? 'bg-slate-50 border-slate-200' : 'bg-slate-900/80 border-slate-800'
              }`}>
                <span className="text-xs font-mono font-bold text-emerald-500 flex items-center gap-1.5">
                  <Box className="w-3.5 h-3.5" /> {activeFile?.name}
                </span>
                <span className="text-[10px] text-slate-400 font-mono">
                  {activeFile?.language || 'json'}
                </span>
              </div>

              <div className="flex-1 p-4 overflow-auto font-mono text-xs leading-relaxed bg-[#0b0e14] text-slate-200">
                <pre className="whitespace-pre">{activeFile?.content}</pre>
              </div>
            </div>
          </div>
        ) : (
          /* Web / Windows / Android Sandbox IFrame Viewer */
          <div className={`flex-1 rounded-2xl border overflow-hidden flex flex-col shadow-sm ${
            isLight ? 'bg-white border-slate-200' : 'bg-[#141a27] border-slate-800'
          }`}>
            <div className={`h-9 px-4 border-b flex items-center justify-between select-none ${
              isLight ? 'bg-slate-50 border-slate-200' : 'bg-slate-900/60 border-slate-800'
            }`}>
              <span className={`text-[11px] font-medium ${isLight ? 'text-slate-600' : 'text-slate-400'}`}>
                Sandbox Preview • {previewType.toUpperCase()}
              </span>
              <div className="flex items-center gap-1.5">
                <span className="w-2.5 h-2.5 rounded-full bg-rose-500/80" />
                <span className="w-2.5 h-2.5 rounded-full bg-amber-500/80" />
                <span className="w-2.5 h-2.5 rounded-full bg-emerald-500/80" />
              </div>
            </div>

            <iframe
              key={iframeKey}
              srcDoc={getSandboxSrcDoc()}
              title="Live Code Sandbox"
              sandbox="allow-scripts allow-modals allow-same-origin"
              className="w-full flex-1 border-none bg-white"
            />
          </div>
        )}
      </div>
    </div>
  );
};
